CREATE TABLE allDialogues (name STRING, line STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' 
TBLPROPERTIES ("skip.header.line.count"="2");
LOAD DATA LOCAL INPATH '/root/inputs/episodeIV_dialouges.txt' INTO TABLE allDialogues;
LOAD DATA LOCAL INPATH '/root/inputs/episodeV_dialouges.txt' INTO TABLE allDialogues;
LOAD DATA LOCAL INPATH '/root/inputs/episodeVI_dialouges.txt' INTO TABLE allDialogues;
SELECT name COUNT(name) AS no_of_lines from allDialogues GROUP BY name ORDER BY no_of_lines;